import math,string,itertools,fractions,heapq,collections,re,array,bisect,random

class ExerciseMachine:
    def getPercentages(self, time):
        
        array = time.split(":")

        seconds = 3600 * int(array[0]) + 60 * int(array[1]) + int(array[2])

        res = 0
        for i in range(1,100):
            if seconds * i % 100 == 0:
                res+=1

        return res

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pf 2.3.0
import sys
import time
def KawigiEdit_RunTest(testNum, p0, hasAnswer, p1):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("\"") + str(p0) + str("\""))
	print(str("]"))
	obj = ExerciseMachine()
	startTime = time.clock()
	answer = obj.getPercentages(p0)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		res = answer == p1
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
		if (hasAnswer):
			print(str("Desired answer:"))
			print(str("\t") + str(p1))
		
		print(str("Your answer:"))
		print(str("\t") + str(answer))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True
tests_disabled = False


# ----- test 0 -----
disabled = False
p0 = "00:30:00"
p1 = 99
all_right = (disabled or KawigiEdit_RunTest(0, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 1 -----
disabled = False
p0 = "00:28:00"
p1 = 19
all_right = (disabled or KawigiEdit_RunTest(1, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 2 -----
disabled = False
p0 = "23:59:59"
p1 = 0
all_right = (disabled or KawigiEdit_RunTest(2, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 3 -----
disabled = False
p0 = "00:14:10"
p1 = 49
all_right = (disabled or KawigiEdit_RunTest(3, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 4 -----
disabled = False
p0 = "00:19:16"
p1 = 3
all_right = (disabled or KawigiEdit_RunTest(4, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

if (all_right):
	if (tests_disabled):
		print(str("You're a stud (but some test cases were disabled)!"))
	else:
		print(str("You're a stud (at least on given cases)!"))
	
else:
	print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
# 
# You are writing firmware for an exercise machine.  Each second, a routine in your firmware is called which decides whether it should display the percentage of the workout completed.  The display does not have any ability to show decimal points, so the routine should only display a percentage if the second it is called results in a whole percentage of the total workout.
# 
# 
# 
# Given a string time representing how long the workout lasts, in the format "hours:minutes:seconds", return the number of times a percentage will be displayed by the routine.  The machine should never display 0% or 100%.
# 
# 
# DEFINITION
# Class:ExerciseMachine
# Method:getPercentages
# Parameters:string
# Returns:integer
# Method signature:def getPercentages(self, time):
# 
# 
# CONSTRAINTS
# -time will be a string formatted as "HH:MM:SS", HH = hours, MM = minutes, SS = seconds.
# -The hours portion of time will be an integer with exactly two digits, with a value between 00 and 23, inclusive.
# -The minutes portion of time will be an integer with exactly two digits, with a value between 00 and 59, inclusive.
# -The seconds portion of time will be an integer with exactly two digits, with a value between 00 and 59, inclusive
# -time will not be "00:00:00".
# 
# 
# EXAMPLES
# 
# 0)
# "00:30:00"
# 
# Returns: 99
# 
# The standard 30 minute workout.  Each one percent increment can be displayed every 18 seconds.
# 
# 1)
# "00:28:00"
# 
# Returns: 19
# 
# The 28 minute workout.  The user completes 5 percent of the workout every 1 minute, 24 seconds.
# 
# 2)
# "23:59:59"
# 
# Returns: 0
# 
# This is the longest workout possible, given the constraints.  No percentages are ever displayed on the screen.
# 
# 3)
# "00:14:10"
# 
# Returns: 49
# 
# 4)
# "00:19:16"
# 
# Returns: 3
# 
# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pf 2.3.0!
