import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class ImageDithering
{
	public int count(String dithered, String[] screen)
	{
		
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, String p0, String[] p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p1[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		ImageDithering obj;
		int answer;
		obj = new ImageDithering();
		long startTime = System.currentTimeMillis();
		answer = obj.count(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
			if (hasAnswer) {
				System.out.println("Desired answer:");
				System.out.println("\t" + p2);
			}
			System.out.println("Your answer:");
			System.out.println("\t" + answer);
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;
		
		String p0;
		String[] p1;
		int p2;
		
		// ----- test 0 -----
		disabled = false;
		p0 = "BW";
		p1 = new String[]{"AAAAAAAA","ABWBWBWA","AWBWBWBA","ABWBWBWA","AWBWBWBA","AAAAAAAA"};
		p2 = 24;
		all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 1 -----
		disabled = false;
		p0 = "BW";
		p1 = new String[]{"BBBBBBBB","BBWBWBWB","BWBWBWBB","BBWBWBWB","BWBWBWBB","BBBBBBBB"};
		p2 = 48;
		all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 2 -----
		disabled = false;
		p0 = "ACEGIKMOQSUWY";
		p1 = new String[]{"ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX","ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX","ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX","ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX","ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX","ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX"};
		p2 = 150;
		all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 3 -----
		disabled = false;
		p0 = "CA";
		p1 = new String[]{"BBBBBBB","BBBBBBB","BBBBBBB"};
		p2 = 0;
		all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 4 -----
		disabled = false;
		p0 = "DCBA";
		p1 = new String[]{"ACBD"};
		p2 = 4;
		all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// 
	// Sometimes when computer programs have a limited number of colors to use, they use a technique called dithering.  Dithering is when you use a pattern made up of different colors such that when the colors are viewed together, they appear like another color.  For example, you can use a checkerboard pattern of black and white pixels to achieve the illusion of gray.
	// 
	// 
	// 
	// You are writing a program to determine how much of the screen is covered by a certain dithered color.  Given a computer screen where each pixel has a certain color, and a list of all the solid colors that make up the dithered color, return the number of pixels on the screen that are used to make up the dithered color.  Each pixel will be represented by a character in screen.  Each character in screen and in dithered will be an uppercase letter ('A'-'Z') representing a color.
	// 
	// 
	// 
	// Assume that any pixel which is a color contained in dithered is part of the dithered color.
	// 
	// 
	// DEFINITION
	// Class:ImageDithering
	// Method:count
	// Parameters:String, String[]
	// Returns:int
	// Method signature:int count(String dithered, String[] screen)
	// 
	// 
	// CONSTRAINTS
	// -dithered will contain between 2 and 26 upper case letters ('A'-'Z'), inclusive.
	// -There will be no repeated characters in dithered.
	// -screen will have between 1 and 50 elements, inclusive.
	// -Each element of screen will contain between 1 and 50 upper case letters ('A'-'Z'), inclusive.
	// -All elements of screen will contain the same number of characters.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// "BW"
	// {"AAAAAAAA",
	//  "ABWBWBWA",
	//  "AWBWBWBA",
	//  "ABWBWBWA",
	//  "AWBWBWBA",
	//  "AAAAAAAA"}
	// 
	// Returns: 24
	// 
	// Here, our dithered color could consist of black (B) and white (W) pixels, composing a shade of gray.  In the picture, there is a dithered gray square surrounded by another color (A).
	// 
	// 1)
	// "BW"
	// {"BBBBBBBB",
	//  "BBWBWBWB",
	//  "BWBWBWBB",
	//  "BBWBWBWB",
	//  "BWBWBWBB",
	//  "BBBBBBBB"}
	// 
	// Returns: 48
	// 
	// Here is the same picture, but with the outer color replaced with black pixels.  Although in reality, the outer pixels do not form a dithered color, your algorithm should still assume they are part of the dithered pattern.
	// 
	// 2)
	// "ACEGIKMOQSUWY"
	// {"ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX",
	//  "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX",
	//  "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX",
	//  "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX",
	//  "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX",
	//  "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX"}
	// 
	// Returns: 150
	// 
	// A picture of vertical stripes, every other stripe is considered part of the dithered color.
	// 
	// 3)
	// "CA"
	// {"BBBBBBB",
	//  "BBBBBBB",
	//  "BBBBBBB"}
	// 
	// Returns: 0
	// 
	// The dithered color is not present.
	// 
	// 4)
	// "DCBA"
	// {"ACBD"}
	// 
	// Returns: 4
	// 
	// The order of the colors doesn't matter.
	// 
	// END KAWIGIEDIT TESTING
}

//Powered by KawigiEdit-pf 2.3.0!
