import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class CCipher
{
	public String decode(String cipherText, int shift)
	{
		String res = new String();
		
		for( int i = 0 ; i < cipherText.length() ; i++ )
		{
			int num = cipherText.charAt(i);
			int num2 = num - shift;
			if( num2 < 'A' )
			{
				res += (char)('Z' - ( 'A' - num2 - 1 ));
			}
			else
			{
				res += (char)num2;
			}
		}
		return res;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, String p0, int p1, boolean hasAnswer, String p2) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + p1);
		System.out.println("]");
		CCipher obj;
		String answer;
		obj = new CCipher();
		long startTime = System.currentTimeMillis();
		answer = obj.decode(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			res = answer.equals(p2);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
			if (hasAnswer) {
				System.out.println("Desired answer:");
				System.out.println("\t" + "\"" + p2 + "\"");
			}
			System.out.println("Your answer:");
			System.out.println("\t" + "\"" + answer + "\"");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;
		
		String p0;
		int p1;
		String p2;
		
		// ----- test 0 -----
		disabled = false;
		p0 = "VQREQFGT";
		p1 = 2;
		p2 = "TOPCODER";
		all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 1 -----
		disabled = false;
		p0 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
		p1 = 10;
		p2 = "QRSTUVWXYZABCDEFGHIJKLMNOP";
		all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 2 -----
		disabled = false;
		p0 = "TOPCODER";
		p1 = 0;
		p2 = "TOPCODER";
		all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 3 -----
		disabled = false;
		p0 = "ZWBGLZ";
		p1 = 25;
		p2 = "AXCHMA";
		all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 4 -----
		disabled = false;
		p0 = "DBNPCBQ";
		p1 = 1;
		p2 = "CAMOBAP";
		all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		// ----- test 5 -----
		disabled = false;
		p0 = "LIPPSASVPH";
		p1 = 4;
		p2 = "HELLOWORLD";
		all_right = (disabled || KawigiEdit_RunTest(5, p0, p1, true, p2) ) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------
		
		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// 
	// Julius Caesar used a system of cryptography, now known as Caesar Cipher, which shifted each letter 2 places further through the alphabet (e.g. 'A' shifts to 'C', 'R' shifts to 'T', etc.). At the end of the alphabet we wrap around, that is 'Y' shifts to 'A'.
	// 
	// We can, of course, try shifting by any number. Given an encoded text and a number of places to shift, decode it.
	// 
	// For example, "TOPCODER" shifted by 2 places will be encoded as "VQREQFGT". In other words, if given (quotes for clarity) "VQREQFGT"  and 2 as input, you will return "TOPCODER". See example 0 below.
	// 
	// 
	// DEFINITION
	// Class:CCipher
	// Method:decode
	// Parameters:String, int
	// Returns:String
	// Method signature:String decode(String cipherText, int shift)
	// 
	// 
	// CONSTRAINTS
	// -cipherText has between 0 to 50 characters inclusive
	// -each character of cipherText is an uppercase letter 'A'-'Z'
	// -shift is between 0 and 25 inclusive
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// "VQREQFGT"
	// 2
	// 
	// Returns: "TOPCODER"
	// 
	// 1)
	// "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	// 10
	// 
	// Returns: "QRSTUVWXYZABCDEFGHIJKLMNOP"
	// 
	// 2)
	// "TOPCODER"
	// 0
	// 
	// Returns: "TOPCODER"
	// 
	// 3)
	// "ZWBGLZ"
	// 25
	// 
	// Returns: "AXCHMA"
	// 
	// 4)
	// "DBNPCBQ"
	// 1
	// 
	// Returns: "CAMOBAP"
	// 
	// 5)
	// "LIPPSASVPH"
	// 4
	// 
	// Returns: "HELLOWORLD"
	// 
	// END KAWIGIEDIT TESTING
}

//Powered by KawigiEdit-pf 2.3.0!
