#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <limits>
#include <tuple>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class PeopleCircle {
public:
	string order(int numMales, int numFemales, int K) {
		
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, bool hasAnswer, string p3) {
	cout << "Test " << testNum << ": [" << p0 << "," << p1 << "," << p2;
	cout << "]" << endl;
	PeopleCircle *obj;
	string answer;
	obj = new PeopleCircle();
	clock_t startTime = clock();
	answer = obj->order(p0, p1, p2);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		res = answer == p3;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
		if (hasAnswer) {
			cout << "Desired answer:" << endl;
			cout << "\t" << "\"" << p3 << "\"" << endl;
		}
		cout << "Your answer:" << endl;
		cout << "\t" << "\"" << answer << "\"" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;
	
	int p0;
	int p1;
	int p2;
	string p3;
	
	// ----- test 0 -----
	disabled = false;
	p0 = 5;
	p1 = 3;
	p2 = 2;
	p3 = "MFMFMFMM";
	all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 1 -----
	disabled = false;
	p0 = 7;
	p1 = 3;
	p2 = 1;
	p3 = "FFFMMMMMMM";
	all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 2 -----
	disabled = false;
	p0 = 25;
	p1 = 25;
	p2 = 1000;
	p3 = "MMMMMFFFFFFMFMFMMMFFMFFFFFFFFFMMMMMMMFFMFMMMFMFMMF";
	all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 3 -----
	disabled = false;
	p0 = 5;
	p1 = 5;
	p2 = 3;
	p3 = "MFFMMFFMFM";
	all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 4 -----
	disabled = false;
	p0 = 1;
	p1 = 0;
	p2 = 245;
	p3 = "M";
	all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// 
// There are numMales males and numFemales females arranged in a circle. Starting from a given point, you count clockwise and remove the K'th person from the circle (where K=1 is the person at the current point, K=2 is the next person in the clockwise direction, etc...).  After removing that person, the next person in the clockwise direction becomes the 
// new starting point.  After repeating this procedure numFemales times, 
// there are no females left in the circle.		
// 
// Given numMales, numFemales and K, your task is to return what the initial arrangement of people in the circle must have been, starting from the starting point and in clockwise order.
// 
// For example, if there are 5 males and 3 females and you remove every second person, your return String will be "MFMFMFMM".
// 
// 
// DEFINITION
// Class:PeopleCircle
// Method:order
// Parameters:int, int, int
// Returns:string
// Method signature:string order(int numMales, int numFemales, int K)
// 
// 
// CONSTRAINTS
// -numMales is between 0 and 25 inclusive
// -numFemales is between 0 and 25 inclusive
// -K is between 1 and 1000 inclusive
// 
// 
// EXAMPLES
// 
// 0)
// 5
// 3
// 2
// 
// Returns: "MFMFMFMM"
// 
// Return "MFMFMFMM". On the first round you remove the second person - "M_MFMFMM". Your new circle looks like "MFMFMMM" from your new starting point. Then you remove the second person again etc.
// 
// 1)
// 7
// 3
// 1
// 
// Returns: "FFFMMMMMMM"
// 
// Starting from the starting point you remove the first person, then you continue and remove the next first person etc. Clearly, all the females are located at the beginning. Hence return "FFFMMMMMMM"
// 
// 2)
// 25
// 25
// 1000
// 
// Returns: "MMMMMFFFFFFMFMFMMMFFMFFFFFFFFFMMMMMMMFFMFMMMFMFMMF"
// 
// 3)
// 5
// 5
// 3
// 
// Returns: "MFFMMFFMFM"
// 
// Here we mark the removed people with '_', and the starting position with lower-case:
// 
// Number of      | People Remaining
// Rounds         | (in initial order)
// ---------------+-----------------
//  0             | mFFMMFFMFM
//  1             | MF_mMFFMFM
//  2             | MF_MM_fMFM
//  3             | MF_MM_FM_m
//  4             | M__mM_FM_M
//  5             | M__MM__m_M
// 
// 
// 
// 4)
// 1
// 0
// 245
// 
// Returns: "M"
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit-pf 2.3.0!
